@startuml
title <size:24>Analytics</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("CoreApplication_boundary", "CoreApplication", $tags="") {
  Container_Boundary("CoreApplication.CoreApplication_boundary", "CoreApplication", $tags="") {
    Component(CoreApplication.CoreApplication.Translation, "Translation", $techn="Module", $descr="", $tags="", $link="")
    Component(CoreApplication.CoreApplication.Analytics, "Analytics", $techn="Module", $descr="", $tags="", $link="")
  }

}

Rel(CoreApplication.CoreApplication.Analytics, CoreApplication.CoreApplication.Translation, "listens to", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml